version: "3.9"

services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./back
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
